
var type = new Typed(".typing-text", {
  strings: [
    "Initializing Hack tool...",
    "FORCE: XX0022. ENCYPT://000.222.2345",
    "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
    "RETRY: REINDEER FLOTILLA",
    "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
    "================================================",
    "Priority 1 // local / scanning...",
    "scanning ports...",
    "IP FOUND (23.45.23.12.00000000)",
    "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
    "DEVICE FOUND (13.66.23.12.00110044)",
    "Connecting To IP ADDRESS:147.1546.4555.5555 /##$DONE##...",
    "SYSTEM ***username*** @.GET(INFO) /##$DONE##...",
    "...",
    "...",
    "BRUTE.EXE -r -z",
    "...locating vulnerabilities...",
    "...vulnerabilities found...",
    "MCP/> DEPLOY CLU",

  ],
  typeSpeed: 10,
  backSpeed: 0,
  cursor: true,
  // loop: true,
  // loopCount: Infinity,
  startDelay: 500,
});

let a = [
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "================================================",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*******////**",
  "****##$$$###***%%%%***",
  "****#////#$$$###*********",
  "*%%%%##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###********////*",
  "****##$$$###****%%%%",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********////",
  "****##$$$###******%%%%",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###******////***",
  "****##$$$###**%%%%****",
  "****##$$$###*********",
  "****##$$$###*****////****",
  "****##$$$###*%%%%*****",
  "****##$$$###*********",
  "****##$$$###*******////**",
  "****##$$$###***%%%%***",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*******////**",
  "****##$$$###***%%%%***",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "****##$$$###*********",
  "-----##$$%%%%##$$-----------",
  "-----##$$%%%%##$$-----------",
  "SCANNING",
  "FORCE: XX0022.ENCYPT://000.222.2345",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME / TICTACTOE / EXECUTE - PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "DEVICE FOUND (13.66.23.12.00110044)",
  "...",
  "...",
  "BRUTE.EXE -r -z",
  "...locating vulnerabilities...",
  "...vulnerabilities found...",
  "MCP/> DEPLOY CLU",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "FORCE: XX0022. ENCYPT://000.222.2345",
  "TRYPASS: ********* AUTH CODE: ALPHA GAMMA: 1___ PRIORITY 1",
  "RETRY: REINDEER FLOTILLA",
  "Z:> /FALKEN/USERNAME/TICTACTOE/ EXECUTE -PLAYERS 0",
  "================================================",
  "Priority 1 // local / scanning...",
  "scanning ports...",
  "IP FOUND (23.45.23.12.00000000)",
  "LOCATION FOUND (E.S.T:13.66.23.12.00110000)",
  "...",
  "...",
  "GETTING ALL DATA ZIP,,,....***************",
  "SCAN: __ Password....@akifh**hhfdal",
  "SCAN: __ IP Address....",
  "SCAN: __ SYSTEM SECURITY,...",
  "SCAN: __ IP:0012.0000.0553.0030",
  "SCAN: __ CID:0100.0000.0554.0080",
  "SCAN: __ PORT:0020.0000.0553.0080",
  "Connecting to Facebook..",
  "GETTING ACCESS ###@USERNAME.... /##$DONE##...",
  "Connecting to server 1...",
  "Connection failed. Retrying...",
  "Connecting to server 2",
  "Connected succesfully...",
  "Username Found..",
  "Trying Brute Force...",
  "200k password tried...",
  "Match not found...",
  "Another 200k password tru=ied...",
  "Match Found...",
  "Accessing all photos,messgages...%##$*******$##%",
  "Accessing Account...",
  "Hack Succesfull..."
];

let string = document.querySelector(".container");

const sleep = async (seconds) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(true);
    }, seconds * 150);
  });
};

const showHack = async (message) => {
  await sleep(2);
  console.log(message);
  string.innerHTML = string.innerHTML + message + "<br>";
};

(async () => {
  for (let i = 0; i < a.length; i++) {
    await showHack(a[i]);
  }
})();

